image: gradle:jdk11
services:
  - postgres:12.2-alpine

variables:
  SONAR_TOKEN: "7b58b4b00b275046d37b5d3c441196a149de07e4"
  SONAR_HOST_URL: "https://pmpl.cs.ui.ac.id/sonarqube/"
#  SONAR_TOKEN: $SONAR_TOKEN
#  SONAR_HOST_URL: $SONAR_HOST_URL
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

Build:
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

Deployment:
  image: ruby:2.6
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  environment:
    name: production
    url: $HEROKU_APP_HOST
  only:
    - master