image: gradle:jdk11
variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
stages:
  - test